[package]
name = "rasterizer-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.5"
fltk = "1.4.33"
log = "0.4.22"
pixels = "0.13.0"
